# Generated by Django 5.2.4 on 2025-11-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyvite', '0002_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAccountMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150, unique=True)),
                ('account_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_header_name', models.CharField(blank=True, help_text='Name to display on fee receipts', max_length=255, null=True)),
                ('receipt_logo', models.ImageField(blank=True, help_text='Logo for receipts', null=True, upload_to='fee_receipts/logos/')),
                ('receipt_address', models.TextField(blank=True, help_text='Address to show on receipt footer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
